using System.Text.Json.Serialization;
using WateryTart.Service.MassClient.Models;
using WateryTart.Service.MassClient.Responses;

namespace WateryTart.Service.MassClient;

/*

IMPORTANT!!!

Unfortunately this file cannot be moved to a source generator, because System.Text.Json's source generator requires the context class to be in the same assembly as the types being serialized. 
This is a limitation of the System.Text.Json source generator, I'm unsure that can be worked around. 

*/
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<object>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(List<Item>))]
[JsonSerializable(typeof(List<Album>))]
[JsonSerializable(typeof(List<Artist>))]
[JsonSerializable(typeof(List<Playlist>))]
[JsonSerializable(typeof(List<Recommendation>))]
[JsonSerializable(typeof(List<Player>))]
[JsonSerializable(typeof(List<PlayerQueue>))]
[JsonSerializable(typeof(List<QueuedItem>))]
[JsonSerializable(typeof(List<Image>))]
[JsonSerializable(typeof(List<ProviderMapping>))]
[JsonSerializable(typeof(List<MetadataLink>))]
[JsonSerializable(typeof(List<List<string>>))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Messages.Auth))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Messages.Message))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Album))]

//Insert stuff from autogenerated version here
[JsonSerializable(typeof(WateryTart.Service.MassClient.Events.BaseEventResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Events.MediaItemEventItem))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Events.MediaItemEventResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Events.PlayerEventResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Events.PlayerQueueEventResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Events.PlayerQueueTimeUpdatedEventResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Messages.Auth))]
//[JsonSerializable(typeof(WateryTart.Service.MassClient.Messages.Commands))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Messages.Message))]
//[JsonSerializable(typeof(WateryTart.Service.MassClient.Messages.MessageJsonContext))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Album))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Artist))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.AudioFormat))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.CurrentMedia))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.DeviceInfo))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.ExtraAttributes))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.ExtraData))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Image))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Item))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Link))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.MediaItem))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Metadata))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.MetadataLink))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Player))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.PlayerQueue))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Playlist))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.ProviderMapping))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.QueuedItem))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Recommendation))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Search))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.SourceList))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Streamdetails))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Auth.AuthUser))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Auth.LoginResults))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Auth.MassCredentials))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Auth.User))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Enums.EventType))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Enums.ImageType))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Enums.MediaType))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Enums.PlaybackState))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Models.Enums.PlayMode))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.AlbumResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.AlbumsResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.ArtistResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.ArtistsResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.AuthResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.CountResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.PlayerQueueItemsResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.PlayerQueueResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.PlayerResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.PlayersQueuesResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.PlaylistResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.PlaylistsResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.RecommendationResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.SearchResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.TempResponse))]
[JsonSerializable(typeof(WateryTart.Service.MassClient.Responses.TracksResponse))]
[JsonSerializable(typeof(ResponseBase<int>))]
[JsonSerializable(typeof(ResponseBase<object>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<WateryTart.Service.MassClient.Models.Album>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<WateryTart.Service.MassClient.Models.Artist>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<WateryTart.Service.MassClient.Models.Item>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<WateryTart.Service.MassClient.Models.Player>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<WateryTart.Service.MassClient.Models.PlayerQueue>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<WateryTart.Service.MassClient.Models.Playlist>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<WateryTart.Service.MassClient.Models.QueuedItem>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<WateryTart.Service.MassClient.Models.Recommendation>>))]
[JsonSerializable(typeof(ResponseBase<WateryTart.Service.MassClient.Models.Album>))]
[JsonSerializable(typeof(ResponseBase<WateryTart.Service.MassClient.Models.Artist>))]
[JsonSerializable(typeof(ResponseBase<WateryTart.Service.MassClient.Models.Auth.AuthUser>))]
[JsonSerializable(typeof(ResponseBase<WateryTart.Service.MassClient.Models.PlayerQueue>))]
[JsonSerializable(typeof(ResponseBase<WateryTart.Service.MassClient.Models.Playlist>))]
[JsonSerializable(typeof(ResponseBase<WateryTart.Service.MassClient.Models.Search>))]
public partial class MassClientJsonContext : JsonSerializerContext
{
}

