name: Publish Update Tester

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: write

jobs:
  linuxbuildarm64:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Setup .NET 10.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
          cache: true
          cache-dependency-path: './src/WateryTart.Platform.Linux/packages.lock.json'
      - name: Install dependencies
        run: dotnet restore src/WateryTart.Platform.Linux
      - run: |
          dotnet publish src/WateryTart.Platform.Linux -p:PublishProfile=LinuxArm /p:Version=1.2.3 -o ./output/linux-arm64
      - name: Set permissions
        run: |
          chmod +x ./output/linux-arm64/WateryTartLinux
      - name: Upload Linux arm64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-build
          path: ./output/linux-arm64

  velopack:
    needs:
      - linuxbuildarm64
      #- macosbuild
    runs-on: ubuntu-latest
    steps:

      - name: Install Velopack
        run: |
          dotnet tool install -g vpk

      - uses: actions/checkout@v6

      - name: Download Linuxarm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-arm64-build
          path: linux-arm64

      - name: Set permissions
        run: |
          chmod +x /home/runner/work/WateryTart/WateryTart/linux-arm64/WateryTartLinux
      - name: Get last release
        run: |  
          vpk download github --repoUrl https://github.com/${{ github.repository }} -c linux-arm64 -o ./releases

      - name: Create Velopack Release
        working-directory: ${{ github.workspace }}
        run: |    
          vpk [linux] pack --packId WateryTart --runtime linux-arm64 --channel linux-arm64 --packVersion 1.2.3 --packDir /home/runner/work/WateryTart/WateryTart/linux-arm64 --exclude '^(*.\dbg|.*\.pdb)$' --mainExe WateryTartLinux --icon Assets/logo_square.png --outputDir ./releases
      
      - name: Upload Linux arm64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-release
          path: ./releases